[HF] add alexandr senyuk
rubizza-camp/mentors-guild pull request #18
Opened 2019-07-03 09:13 UTC by alexandr-senyuk

2019-07-06 20:43 UTC, anatoliliotych requested changes

2019-07-06 20:43 UTC, anatoliliotych commented on 2019/Senyuk_Alexandr.md
> +
remove empty line :)

2019-07-26 15:10 UTC, alexandr-senyuk commented on 2019/Senyuk_Alexandr.md
> +
@anatoliliotych, I've done!

2019-07-26 15:14 UTC, mrgrecha approved these changes
LGTM

2019-07-26 16:27 UTC, davydovanton approved these changes

2019-07-27 06:45 UTC, anatoliliotych approved these changes

2019-07-27 06:45 UTC, merged